### ISSUE TITLE
Update on newest Flighradar24 Software

### ISSUE THREAD

**Issue by ghost** [Liggy/fr24feed#1]
Hi Liggy,

your Docker version is working great on my Synology x86-64. Would it be possible to get an updated to 1.0.23-8?

Thanks in advance

**Comment by Liggy** [comment]
Hi MobiusOne91,

if I'm not mistaken, 1.0.23-8 is only available for the armhf platform. On the amd64 platform for Linux they only offer 1.0.18-5. At least that's what I find [here](https://www.flightradar24.com/share-your-data) on the Linux tab and also on their Debian apt repository [here](http://repo.feed.flightradar24.com/).
