### ISSUE TITLE
No aircraft information uploaded

### ISSUE THREAD

**Issue by the-holger** [Liggy/fr24feed#3]
Hi! I just set up your (wonderfully small!) Docker image and tracking aircraft worked right away.
However the feeder status page shows that no aircraft information is uploaded.
Is there anything I need to do on my host to enable this?

Trying to figure it out on my own I stumbled across forum posts saying that its a problem with ipv6, but those answers revolve around the raspberry pi...

Thank you!

**Comment by Liggy** [comment]
I just checked my status page and it also lists 4 tracked and 0 uploaded aircrafts. However when I look at my FR24 account [data sharing](https://www.flightradar24.com/account/data-sharing) it clearly indicates that several aircrafts were seen and positions reported.
Can you see tracked aircrafts when you check the dump1090 URL of your docker container? Maybe it's just a wrong display or something in the aircraft data is incomplete, so it cannot be sent?
Another check could be looking for errors in the docker logs. Unfortunately I can only guess here as I'm not familiar with how the actual feeder works.

Schönen Gruß

**Comment by Liggy** [comment]
No more feedback -> Closed
